#the compose file version
version: "3.8"

services:

  webserver:
    image: nginx:stable-alpine
    container_name: felstore_nginx
    restart: unless-stopped
    ports:
      #local port : nginx
      - "8080:80"
    volumes:
      # current dir : nginx dir 
      - .:/var/www/html
      #default config, common for laravel
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    #what the webserver depends on
    depends_on: 
      - php
      - mysql
    #where this service connects(.yml networks)
    networks:
      - felstore

  #.env DB_HOST= shall have this service
  mysql:
    image: mysql:8.0.21
    container_name: felstore_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "33061:3306"
    environment: 
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes: 
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/mysql-custom.cnf
    networks:
      - felstore

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: felstore_PMA
    depends_on:
      - mysql
    ports:
      - "8082:80"
    environment:
      - PMA_HOST=${DB_HOST}
    networks:
      - felstore

  php:
    build:
      context: .
      #this dockerfile has the php image with its extensions
      dockerfile: ./docker/php/php.dockerfile
    container_name: felstore_php
    volumes: 
      - .:/var/www/html
    ports: 
      - "9000:9000"
    networks:
      - felstore
       
  redis:
    image: redis
    restart: unless-stopped
    container_name: felstore_redis
    volumes:
      - ./docker/redis/data:/data
    networks:
      - felstore

  composer:
    image: composer:latest
    container_name: felstore_composer
    volumes: 
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on: 
      - php
    networks:
      - felstore    

  #setup npm with node
  npm:
    image: node:14.9
    container_name: felstore_npm
    volumes: 
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  #setup artisan with php
  artisan:
    build: 
      context: .
      dockerfile: ./docker/php/php.dockerfile
    container_name: felstore_artisan
    volumes: 
      - .:/var/www/html
    depends_on: 
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php','/var/www/html/artisan']
    networks:
      - felstore

networks:
  felstore: